### PR TITLE
quick versioning readme file update

### PR DESCRIPTION
**Pull request by mannyhenri**
simply added version of the package plus a bit more details what's included. Also added a notes.txt in the .gitignore as this will be where I'll document steps, tutorials, progress and comments on Apollo (to share with the community soon).

### CODE REVIEW

**Comment by stubailo** [comment]
Thanks!

**Comment by p4bloch** [comment]
This does not seem to be rendered properly on github markdown
image

I suggest we highlight this as a code block

```
├── client                  # Client files
│   ├── main.css            # Styles
│   ├── main.html           # First loaded view pulling from imports
│   └── main.js             # Imports all required files - React render
├── imports                 # A client/server folder
│   ├── api                 #
│   |  └── schema.js        # Schema & query definitions
│   └── ui                  #
│      └── App.js           # UI React rendering
├── server                  # Server files
│   └── server.js           # Main server file initiating Apollo server
└── package.json            # node dependencies
```

**Comment by stubailo** [comment]
Good point. I should have looked at the preview.

**Comment by mannyhenri** [comment]
Yeah I sent a fix right after, so #15 fixes it, which has now been merged.

**Pull request merged**
