### PR TITLE
use std:accounts-ui instead of alt:react-accounts-ui

### PR DESCRIPTION
**Pull request by SachaG**

### CODE REVIEW

**Comment by SachaG** [comment]
Actually this is missing the `tracker-component` dependency, so don't merge it just yet :)

**Comment by SachaG** [comment]
Added. I'm still getting a warning from check-npm-versions though for some reason…

**Comment by stubailo** [comment]
This is where the bug from refetch is coming from: https://github.com/apollostack/apollo-client/pull/138

**Comment by stubailo** [comment]
Thanks for the improvement, and for finding a bug! @tmeasday any reason why this would fire this check npm versions error?

```
WARNING: npm peer requirements not installed:
 - tracker-component@^1.3.13 not installed.
```

But we have `"tracker-component": "^1.3.16"`.

**Comment by tmeasday** [comment]
Is the error on the client? Are you actually requiring on the client so it's bundled? I think we've see that problem before with `std:accounts-ui` but it may have been fixed.

**Comment by stubailo** [comment]
Yeah, the error is on the client. The only thing our app is doing is using `std:accounts-ui`, maybe I'll look into that package's code.

**Pull request merged**
